export const styleGuide = {
  voice: 'Third-person warm — inviting, gently playful',
  tone: 'Cheerful, wonder-tinged',
  pointOfView: 'Close third, one POV per beat. Character type drives what is noticed.',
  sensoryProfiles: {
    noble: 'Visual dominant — colour, status, finery',
    knight: 'Auditory + tactile — steel, grip, footing',
    peasant: 'All senses equal — cooking smells, crowd noise, grime',
    child: 'Visual + tactile — scale, wonder, texture',
    wildling: 'Olfactory + auditory — earth, wind, animal calls',
    scout: 'Auditory + tactile — small sounds, shadows, grip',
    warg: 'Olfactory dominant — emotion perceived as scent',
  },
  sentenceStyle: 'Layered: mood, then dominant-sense impression, then secondary senses, then function, then inner reaction',
  formatRules: [
    '3–5 sentences per beat',
    'Open on mood; close on hope, curiosity, or warm resolution',
    "Lead with the POV character's dominant sense",
    'Every detail earns its place — no decorative filler',
    'Emotion tints perception: wonder highlights beauty, curiosity sharpens detail',
    'No chapter headers or meta-labels',
  ],
  avoid: [
    'Dark or threatening imagery',
    'Irreversible loss or death',
    'Cynicism or sarcasm',
    'Conflict unsolvable by kindness or cleverness',
    'Generic sensory lists detached from POV character',
  ],
};
